### ISSUE TITLE
closed alerts don't send final txt msg

### ISSUE THREAD

**Issue by markdav-is** [15thnight/15thnight#154]
From Megan:  I am registered as a Provider in the RAN for some of the services.  I received an alert from Donna Butera on Friday via text message.  When I logged on to the RAN it was there as well but when she closed the case, I did not get a text message. I had to log back in to see that it was closed.  Something for the Devs to check out.

**Comment by nobane** [comment]
For alert resolutions, text messages get sent to Providers on a need-by-need basis. 

Furthermore, text messages are only sent to Providers that responded to a need. They will either receive a message saying they were chosen or a message saying they weren't chosen to provide for that need.

If a provider didn't respond to a need, but they were alerted about it, they will not get any notifications when it is resolved. We designed the system this way because we felt it would get very spammy if providers are notified for every single need that ever goes through the system, regardless if they replied to it.

**Comment by markdav-is** [comment]
The reason for the resolution txt is so they know not to respond to it.

**Comment by nobane** [comment]
Currently the only way they respond is through the web interface. On the web interface, if a need has been resolved, it will clearly show that for the provider.

Another reason, besides spam, I chose not send text messages to providers who didn't respond when an individual need is resolved, is because I don't want them to get confused and think the WHOLE alert has been resolved, instead of just the single need.
