### ISSUE TITLE
Description box character limit

### ISSUE THREAD

**Issue by TCAleap** [15thnight/15thnight#182]
There must be a character limit in the description box because you will get an error message if you go over.  We need to tell people what the character limit is or not have a limit.

**Comment by nobane** [comment]
We can do either, have no limit or impose a limit.

I'm more inclined to impose a limit, simply because this description is going to be inserted into a text message. I think it would be good to try to enforce keeping these messages short (perhaps 100 characters or less?) because of the text message thing. Long text messages get truncated into multiple text messages on some phones, and sometimes those multiple messages arrive out of order. 

When there is only 2-3 messages for one alert, it is easy enough to figure out their order if they came in out of order. However, when a description so long causes 4+ text messages to arrive, possibly out of order, it may be confusing or hard to determine what the message was for the end user.

**Comment by nobane** [comment]
@TCAleap please see my comment above and respond with what is desired for us to build (limit or no limit).

**Comment by TCAleap** [comment]
I support your suggestion to impose a word limit in the description box.  We just need a way to communicate that limit in the description box.
Megan

**Comment by oslcit** [comment]
I think the char limit currently is around 200. It could even stay unchanged and be fine. The issue we were running into is that going over the limit would cause an error. Unfortunately, that error was not descriptive and gave no indication that it was a char limit issue. So, one solution might be to add a note to the description box stating that the char limit is 200 and to make the error be more detailed so that the user knows that they need to adjust their description.

**Comment by nobane** [comment]
I am reopening this issue because the bug hasn't been fixed. Watch out of the `Close and comment` button, it closes the issue.

We will keep the limit at 200 and provide feedback for the user that it is too long, and state the limit. Thanks for the quick responses.

**Comment by TCAleap** [comment]
Thank you, Garrett!!!
